### ISSUE TITLE
Task = Event and possibly Routine?

### ISSUE THREAD

**Issue by sxia1** [jwongUlti25/FermentedAgaveJuice#3]
I don't think there are any differences between Task and Event. However, after thinking about this some more, perhaps we should introduce a Routine class. This is because we have a method that determines when the user has free time. The user can't be expected to put at work or sleeping as a task/event for every single day. So if we have a routine class, it will automatically apply it to all applicable days. Then the method determining free time will not include all the time when the user is usually sleeping, working etc. Then these routines can have their own optional notification that will alert them regularly.

**Comment by johnnywong30** [comment]
We decided that Events are the same as both Routines and Tasks.
